---

- name: Run tasks against localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes

  - name: Install deps
    apt:
      name: "{{ lookup('file', '{{ playbook_dir }}/pkgs.txt') }}"
